on:
   workflow_dispatch 

name: Tests

jobs:
  document:
    name: run tests
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat
          needs: pr-document
          
      - name: run test
        run: testthat::test_dir("tests/testthat/")
        shell: Rscript {0}
